#!/bin/sh
# script to install a binary using cargo but
# building it remotely.
set -e

if [ -z "$CLOUD_USER" ] || [ -z "$CLOUD_USER" ]; then
	echo "You must provide \$CLOUD_HOST and \$CLOUD_USER" 2>&1
	exit 1
fi

# when running with cargo cloudinstall ... cargo
# passes cloudinstall as the first paramater,
# thus we need to ignoere it here.
cmd="$@"
if [ "$1" = "cloudinstall" ]; then
    cmd=${@:2}
fi

ssh -t "$CLOUD_USER@$CLOUD_HOST"        \
       "source ~/.profile              ;\
			 dir=\$(mktemp -d)               ;\
			 trap \"rm -rf \$dir\"           ;\
       cargo install $cmd --root \$dir"

rsync -vz --info=progress2 -e \
    "ssh -l '$CLOUD_USER'" "$CLOUD_HOST:$TARGET" ~/.cargo/bin
